// Generated by tools/generate_room_access.py; native simulation scalars only.
package fe.unit {
public class RConnectUnitAccess {
public static function capture(u:Unit):Object {
var s:Object={xml:u.mapxml==null?null:u.mapxml.toXMLString(),ai:u.aiState,groups:{}};
if(u is Mine) s.groups.Mine={aiN:(u as Mine).aiN};
if(u is Unit) s.groups.Unit={uniqName:(u as Unit).uniqName,t_hp:(u as Unit).t_hp,aiNapr:(u as Unit).aiNapr,aiVNapr:(u as Unit).aiVNapr,aiTTurn:(u as Unit).aiTTurn,aiPlav:(u as Unit).aiPlav,aiState:(u as Unit).aiState,aiTCh:(u as Unit).aiTCh,aiSpok:(u as Unit).aiSpok,maxSpok:(u as Unit).maxSpok,timerDie:(u as Unit).timerDie,t_hitPart:(u as Unit).t_hitPart,hitSumm:(u as Unit).hitSumm,t_mess:(u as Unit).t_mess,kolChild:(u as Unit).kolChild};
if(u is UnitAIRobot) s.groups.UnitAIRobot={weap:(u as UnitAIRobot).weap,isPort:(u as UnitAIRobot).isPort,t_port:(u as UnitAIRobot).t_port,kol_port:(u as UnitAIRobot).kol_port,aiAttackT:(u as UnitAIRobot).aiAttackT,aiAttackOch:(u as UnitAIRobot).aiAttackOch,aiDist:(u as UnitAIRobot).aiDist};
if(u is UnitAlicorn) s.groups.UnitAlicorn={floatX:(u as UnitAlicorn).floatX,floatY:(u as UnitAlicorn).floatY,shitMaxHp:(u as UnitAlicorn).shitMaxHp,superSilaTip:(u as UnitAlicorn).superSilaTip,tGotov:(u as UnitAlicorn).tGotov,tUsed:(u as UnitAlicorn).tUsed,tSuper:(u as UnitAlicorn).tSuper,tNomater:(u as UnitAlicorn).tNomater,superInvis:(u as UnitAlicorn).superInvis,curA:(u as UnitAlicorn).curA,celA:(u as UnitAlicorn).celA,tTeleThrow:(u as UnitAlicorn).tTeleThrow,tTeleRes:(u as UnitAlicorn).tTeleRes,throwForce:(u as UnitAlicorn).throwForce,teleX:(u as UnitAlicorn).teleX,teleY:(u as UnitAlicorn).teleY,teleSpeed:(u as UnitAlicorn).teleSpeed,teleAccel:(u as UnitAlicorn).teleAccel,derp:(u as UnitAlicorn).derp,tlColor:(u as UnitAlicorn).tlColor,nmColor:(u as UnitAlicorn).nmColor,blasted:(u as UnitAlicorn).blasted,osob:(u as UnitAlicorn).osob,t_pole:(u as UnitAlicorn).t_pole,optDistAtt:(u as UnitAlicorn).optDistAtt,optDistTele:(u as UnitAlicorn).optDistTele,stalkDist:(u as UnitAlicorn).stalkDist,aiAttackT:(u as UnitAlicorn).aiAttackT,t_landing:(u as UnitAlicorn).t_landing,t_float:(u as UnitAlicorn).t_float,t_fall:(u as UnitAlicorn).t_fall,t_nomater:(u as UnitAlicorn).t_nomater,t_shit:(u as UnitAlicorn).t_shit,t_gotov:(u as UnitAlicorn).t_gotov,t_super:(u as UnitAlicorn).t_super,t_tele:(u as UnitAlicorn).t_tele,t_alarm:(u as UnitAlicorn).t_alarm};
if(u is UnitAnt) s.groups.UnitAnt={optDistAtt:(u as UnitAnt).optDistAtt,optJumping:(u as UnitAnt).optJumping,optJumpAtt:(u as UnitAnt).optJumpAtt,optAnimAtt:(u as UnitAnt).optAnimAtt,t_punch:(u as UnitAnt).t_punch,vstorona:(u as UnitAnt).vstorona,aiLaz:(u as UnitAnt).aiLaz,aiNeedLaz:(u as UnitAnt).aiNeedLaz};
if(u is UnitBat) s.groups.UnitBat={tr:(u as UnitBat).tr,aiDx:(u as UnitBat).aiDx,aiDy:(u as UnitBat).aiDy,aiRasst:(u as UnitBat).aiRasst};
if(u is UnitBloat) s.groups.UnitBloat={cDam:(u as UnitBloat).cDam,isEmit:(u as UnitBloat).isEmit,gryz:(u as UnitBloat).gryz,isGryz:(u as UnitBloat).isGryz,shootCh:(u as UnitBloat).shootCh,aiDx:(u as UnitBloat).aiDx,aiDy:(u as UnitBloat).aiDy,aiRasst:(u as UnitBloat).aiRasst,attRasst:(u as UnitBloat).attRasst,attCh:(u as UnitBloat).attCh};
if(u is UnitBloatEmitter) s.groups.UnitBloatEmitter={emitId:(u as UnitBloatEmitter).emitId,emit_t:(u as UnitBloatEmitter).emit_t};
if(u is UnitBossAlicorn) s.groups.UnitBossAlicorn={weap:(u as UnitBossAlicorn).weap,shitMaxHp:(u as UnitBossAlicorn).shitMaxHp,isShit:(u as UnitBossAlicorn).isShit,isBlast:(u as UnitBossAlicorn).isBlast,t_float:(u as UnitBossAlicorn).t_float,floatX:(u as UnitBossAlicorn).floatX,floatY:(u as UnitBossAlicorn).floatY,throwForce:(u as UnitBossAlicorn).throwForce,teleX:(u as UnitBossAlicorn).teleX,teleY:(u as UnitBossAlicorn).teleY,teleSpeed:(u as UnitBossAlicorn).teleSpeed,teleAccel:(u as UnitBossAlicorn).teleAccel,derp:(u as UnitBossAlicorn).derp,optDistTele:(u as UnitBossAlicorn).optDistTele,superInvis:(u as UnitBossAlicorn).superInvis,curA:(u as UnitBossAlicorn).curA,celA:(u as UnitBossAlicorn).celA,emit_t:(u as UnitBossAlicorn).emit_t,moveX:(u as UnitBossAlicorn).moveX,moveY:(u as UnitBossAlicorn).moveY,attState:(u as UnitBossAlicorn).attState,t_turn:(u as UnitBossAlicorn).t_turn,t_shit:(u as UnitBossAlicorn).t_shit,t_fly:(u as UnitBossAlicorn).t_fly};
if(u is UnitBossDron) s.groups.UnitBossDron={shitMaxHp:(u as UnitBossDron).shitMaxHp,emit_t:(u as UnitBossDron).emit_t,moveX:(u as UnitBossDron).moveX,moveY:(u as UnitBossDron).moveY,t_atk:(u as UnitBossDron).t_atk,t_shit:(u as UnitBossDron).t_shit,kolth:(u as UnitBossDron).kolth,speedBonus:(u as UnitBossDron).speedBonus};
if(u is UnitBossEncl) s.groups.UnitBossEncl={weap:(u as UnitBossEncl).weap,minY:(u as UnitBossEncl).minY,maxY:(u as UnitBossEncl).maxY,minX:(u as UnitBossEncl).minX,maxX:(u as UnitBossEncl).maxX,sinX:(u as UnitBossEncl).sinX,sinDX:(u as UnitBossEncl).sinDX,emit_t:(u as UnitBossEncl).emit_t};
if(u is UnitBossNecr) s.groups.UnitBossNecr={atk_t:(u as UnitBossNecr).atk_t,throu_t:(u as UnitBossNecr).throu_t,atk_n:(u as UnitBossNecr).atk_n,prot_n:(u as UnitBossNecr).prot_n,protculd_t:(u as UnitBossNecr).protculd_t,curseculd_t:(u as UnitBossNecr).curseculd_t,prot_t:(u as UnitBossNecr).prot_t,healHp:(u as UnitBossNecr).healHp,isShadow:(u as UnitBossNecr).isShadow,superInvis:(u as UnitBossNecr).superInvis,curA:(u as UnitBossNecr).curA,celA:(u as UnitBossNecr).celA};
if(u is UnitBossRaider) s.groups.UnitBossRaider={weap:(u as UnitBossRaider).weap,aiLaz:(u as UnitBossRaider).aiLaz,aiJump:(u as UnitBossRaider).aiJump,aiAttack:(u as UnitBossRaider).aiAttack,attackerType:(u as UnitBossRaider).attackerType,aiAttackT:(u as UnitBossRaider).aiAttackT,aiAttackOch:(u as UnitBossRaider).aiAttackOch,aiDist:(u as UnitBossRaider).aiDist,aiVKurse:(u as UnitBossRaider).aiVKurse,t_chCel:(u as UnitBossRaider).t_chCel,emit_t:(u as UnitBossRaider).emit_t};
if(u is UnitBossUltra) s.groups.UnitBossUltra={weap:(u as UnitBossUltra).weap,shitMaxHp:(u as UnitBossUltra).shitMaxHp,usil:(u as UnitBossUltra).usil,emit_t:(u as UnitBossUltra).emit_t,moveX:(u as UnitBossUltra).moveX,moveY:(u as UnitBossUltra).moveY,attState:(u as UnitBossUltra).attState,t_turn:(u as UnitBossUltra).t_turn,t_shit:(u as UnitBossUltra).t_shit};
if(u is UnitCaptive) s.groups.UnitCaptive={tr:(u as UnitCaptive).tr,sr:(u as UnitCaptive).sr,novoi:(u as UnitCaptive).novoi};
if(u is UnitDamager) s.groups.UnitDamager={tr:(u as UnitDamager).tr,weap:(u as UnitDamager).weap,tipDamager:(u as UnitDamager).tipDamager,status:(u as UnitDamager).status,needSkill:(u as UnitDamager).needSkill,isAct:(u as UnitDamager).isAct,allid:(u as UnitDamager).allid,och:(u as UnitDamager).och,noch:(u as UnitDamager).noch,kolammo:(u as UnitDamager).kolammo,damageExpl:(u as UnitDamager).damageExpl,destroyExpl:(u as UnitDamager).destroyExpl,explRadius:(u as UnitDamager).explRadius,aiN:(u as UnitDamager).aiN};
if(u is UnitDestr) s.groups.UnitDestr={tr:(u as UnitDestr).tr,t_part:(u as UnitDestr).t_part};
if(u is UnitDron) s.groups.UnitDron={br:(u as UnitDron).br,stuk:(u as UnitDron).stuk,weap:(u as UnitDron).weap,atkDist:(u as UnitDron).atkDist,aiAgr:(u as UnitDron).aiAgr,floatX:(u as UnitDron).floatX,floatY:(u as UnitDron).floatY,t_float:(u as UnitDron).t_float,atkRasst:(u as UnitDron).atkRasst,t_krut:(u as UnitDron).t_krut};
if(u is UnitEncl) s.groups.UnitEncl={t_gren:(u as UnitEncl).t_gren};
if(u is UnitEqd) s.groups.UnitEqd={jump_n:(u as UnitEqd).jump_n};
if(u is UnitFish) s.groups.UnitFish={aiDx:(u as UnitFish).aiDx,aiDy:(u as UnitFish).aiDy,aiRasst:(u as UnitFish).aiRasst};
if(u is UnitHellhound) s.groups.UnitHellhound={vDestroy:(u as UnitHellhound).vDestroy,nuh:(u as UnitHellhound).nuh,aiJump:(u as UnitHellhound).aiJump,aiLaz:(u as UnitHellhound).aiLaz,t_laz:(u as UnitHellhound).t_laz,r_laz:(u as UnitHellhound).r_laz};
if(u is UnitMerc) s.groups.UnitMerc={t_gren:(u as UnitMerc).t_gren};
if(u is UnitMonstrik) s.groups.UnitMonstrik={optDistAtt:(u as UnitMonstrik).optDistAtt,optJumping:(u as UnitMonstrik).optJumping,optJumpAtt:(u as UnitMonstrik).optJumpAtt,optAnimAtt:(u as UnitMonstrik).optAnimAtt,t_punch:(u as UnitMonstrik).t_punch};
if(u is UnitMsp) s.groups.UnitMsp={weap:(u as UnitMsp).weap,cep:(u as UnitMsp).cep};
if(u is UnitMWall) s.groups.UnitMWall={rearm:(u as UnitMWall).rearm};
if(u is UnitNecros) s.groups.UnitNecros={br:(u as UnitNecros).br};
if(u is UnitNPC) s.groups.UnitNPC={t_ref:(u as UnitNPC).t_ref,t_anim:(u as UnitNPC).t_anim,t_float:(u as UnitNPC).t_float,floatX:(u as UnitNPC).floatX,floatY:(u as UnitNPC).floatY,wait:(u as UnitNPC).wait,dey:(u as UnitNPC).dey,cx:(u as UnitNPC).cx,cy:(u as UnitNPC).cy};
if(u is UnitPhoenix) s.groups.UnitPhoenix={t_fall:(u as UnitPhoenix).t_fall};
if(u is UnitPonPon) s.groups.UnitPonPon={tr:(u as UnitPonPon).tr,act:(u as UnitPonPon).act,novoi:(u as UnitPonPon).novoi,verVis:(u as UnitPonPon).verVis,privet:(u as UnitPonPon).privet};
if(u is UnitProtect) s.groups.UnitProtect={jump_n:(u as UnitProtect).jump_n,jump_m:(u as UnitProtect).jump_m};
if(u is UnitRaider) s.groups.UnitRaider={weap:(u as UnitRaider).weap,visionMult:(u as UnitRaider).visionMult,baseDexter:(u as UnitRaider).baseDexter,floatX:(u as UnitRaider).floatX,floatY:(u as UnitRaider).floatY,aiLaz:(u as UnitRaider).aiLaz,aiJump:(u as UnitRaider).aiJump,aiAttack:(u as UnitRaider).aiAttack,attackerType:(u as UnitRaider).attackerType,aiAttackT:(u as UnitRaider).aiAttackT,aiAttackOch:(u as UnitRaider).aiAttackOch,aiDist:(u as UnitRaider).aiDist,stalkDist:(u as UnitRaider).stalkDist,aiVKurse:(u as UnitRaider).aiVKurse,t_chCel:(u as UnitRaider).t_chCel,emit_t:(u as UnitRaider).emit_t,t_laz:(u as UnitRaider).t_laz,r_laz:(u as UnitRaider).r_laz,t_landing:(u as UnitRaider).t_landing,t_float:(u as UnitRaider).t_float,t_fall:(u as UnitRaider).t_fall,t_turn:(u as UnitRaider).t_turn,tstor:(u as UnitRaider).tstor,plusObservOk:(u as UnitRaider).plusObservOk,plusObserv:(u as UnitRaider).plusObserv};
if(u is UnitRanger) s.groups.UnitRanger={t_gren:(u as UnitRanger).t_gren};
if(u is UnitRoller) s.groups.UnitRoller={rollDr:(u as UnitRoller).rollDr,tr:(u as UnitRoller).tr,optDistAtt:(u as UnitRoller).optDistAtt,optJumpAtt:(u as UnitRoller).optJumpAtt};
if(u is UnitScythe) s.groups.UnitScythe={napr:(u as UnitScythe).napr,dr:(u as UnitScythe).dr,t:(u as UnitScythe).t,por:(u as UnitScythe).por,bindRad:(u as UnitScythe).bindRad,aiN:(u as UnitScythe).aiN};
if(u is UnitSentinel) s.groups.UnitSentinel={jump_n:(u as UnitSentinel).jump_n};
if(u is UnitSlime) s.groups.UnitSlime={pluh:(u as UnitSlime).pluh,tr:(u as UnitSlime).tr,isMine:(u as UnitSlime).isMine,explDist:(u as UnitSlime).explDist,isExpl:(u as UnitSlime).isExpl,aiN:(u as UnitSlime).aiN};
if(u is UnitSpectre) s.groups.UnitSpectre={br:(u as UnitSpectre).br};
if(u is UnitSpriteBot) s.groups.UnitSpriteBot={cDam:(u as UnitSpriteBot).cDam,aiDx:(u as UnitSpriteBot).aiDx,aiDy:(u as UnitSpriteBot).aiDy,aiRasst:(u as UnitSpriteBot).aiRasst};
if(u is UnitThunderHead) s.groups.UnitThunderHead={shitMaxHp:(u as UnitThunderHead).shitMaxHp,emit_t:(u as UnitThunderHead).emit_t,moveX:(u as UnitThunderHead).moveX,moveY:(u as UnitThunderHead).moveY,t_atk:(u as UnitThunderHead).t_atk,t_shit:(u as UnitThunderHead).t_shit,kolth:(u as UnitThunderHead).kolth,speedBonus:(u as UnitThunderHead).speedBonus,limX:(u as UnitThunderHead).limX,limY:(u as UnitThunderHead).limY,t_moln:(u as UnitThunderHead).t_moln,isAtt:(u as UnitThunderHead).isAtt,kol_emit:(u as UnitThunderHead).kol_emit,max_emit:(u as UnitThunderHead).max_emit,t_die:(u as UnitThunderHead).t_die,t_vsos:(u as UnitThunderHead).t_vsos,vsos_max:(u as UnitThunderHead).vsos_max,vsos_porog:(u as UnitThunderHead).vsos_porog,vsos_force:(u as UnitThunderHead).vsos_force,ugol:(u as UnitThunderHead).ugol,distanc:(u as UnitThunderHead).distanc};
if(u is UnitThunderTurret) s.groups.UnitThunderTurret={bindX:(u as UnitThunderTurret).bindX,bindY:(u as UnitThunderTurret).bindY,attTurN:(u as UnitThunderTurret).attTurN,t_wait:(u as UnitThunderTurret).t_wait};
if(u is UnitTrain) s.groups.UnitTrain={tr:(u as UnitTrain).tr};
if(u is UnitTransmitter) s.groups.UnitTransmitter={cDam:(u as UnitTransmitter).cDam,dist:(u as UnitTransmitter).dist,distdam:(u as UnitTransmitter).distdam,upKoef:(u as UnitTransmitter).upKoef,prevKoef:(u as UnitTransmitter).prevKoef,cep:(u as UnitTransmitter).cep};
if(u is UnitTrap) s.groups.UnitTrap={rearm:(u as UnitTrap).rearm,aiN:(u as UnitTrap).aiN};
if(u is UnitTrigger) s.groups.UnitTrigger={status:(u as UnitTrigger).status,trapT:(u as UnitTrigger).trapT,ax1:(u as UnitTrigger).ax1,ax2:(u as UnitTrigger).ax2,ay1:(u as UnitTrigger).ay1,ay2:(u as UnitTrigger).ay2,trapL:(u as UnitTrigger).trapL,needSkill:(u as UnitTrigger).needSkill,isAct:(u as UnitTrigger).isAct,one:(u as UnitTrigger).one,allid:(u as UnitTrigger).allid,allact:(u as UnitTrigger).allact,vNoise:(u as UnitTrigger).vNoise,res:(u as UnitTrigger).res,aiN:(u as UnitTrigger).aiN};
if(u is UnitTurret) s.groups.UnitTurret={turrettip:(u as UnitTurret).turrettip,hidden:(u as UnitTurret).hidden,sleep:(u as UnitTurret).sleep,reprog:(u as UnitTurret).reprog,actDrot:(u as UnitTurret).actDrot,noTurn:(u as UnitTurret).noTurn,absVis:(u as UnitTurret).absVis,watchDrot:(u as UnitTurret).watchDrot,period:(u as UnitTurret).period,nRot:(u as UnitTurret).nRot,angle:(u as UnitTurret).angle};
if(u is UnitVortex) s.groups.UnitVortex={br:(u as UnitVortex).br};
if(u is UnitZebra) s.groups.UnitZebra={shine:(u as UnitZebra).shine,shine2:(u as UnitZebra).shine2,red:(u as UnitZebra).red};
if(u is UnitZombie) s.groups.UnitZombie={superX:(u as UnitZombie).superX,superY:(u as UnitZombie).superY,glowTip:(u as UnitZombie).glowTip,knocked2:(u as UnitZombie).knocked2,superSilaTip:(u as UnitZombie).superSilaTip,tZlo:(u as UnitZombie).tZlo,tPrepSuper:(u as UnitZombie).tPrepSuper,tSuper:(u as UnitZombie).tSuper,vJump:(u as UnitZombie).vJump,teleAccel:(u as UnitZombie).teleAccel,teleSpeed:(u as UnitZombie).teleSpeed,vDestroy:(u as UnitZombie).vDestroy,radMin:(u as UnitZombie).radMin,radMax:(u as UnitZombie).radMax,radradMin:(u as UnitZombie).radradMin,radradMax:(u as UnitZombie).radradMax,radHeal:(u as UnitZombie).radHeal,superQuake:(u as UnitZombie).superQuake,super_on:(u as UnitZombie).super_on,tIsRes:(u as UnitZombie).tIsRes,t_res:(u as UnitZombie).t_res,t_ca:(u as UnitZombie).t_ca,aiJump:(u as UnitZombie).aiJump,aiZlo:(u as UnitZombie).aiZlo,optDistAtt:(u as UnitZombie).optDistAtt};
return s;
}
public static function restore(u:Unit,s:Object):void {
if(s==null || s.groups==null)return;
if(u is Mine && s.groups.Mine!=null) {
if(s.groups.Mine.aiN!==undefined)(u as Mine).aiN=int(s.groups.Mine.aiN);
}
if(u is Unit && s.groups.Unit!=null) {
if(s.groups.Unit.uniqName!==undefined)(u as Unit).uniqName=Boolean(s.groups.Unit.uniqName);
if(s.groups.Unit.t_hp!==undefined)(u as Unit).t_hp=int(s.groups.Unit.t_hp);
if(s.groups.Unit.aiNapr!==undefined)(u as Unit).aiNapr=int(s.groups.Unit.aiNapr);
if(s.groups.Unit.aiVNapr!==undefined)(u as Unit).aiVNapr=int(s.groups.Unit.aiVNapr);
if(s.groups.Unit.aiTTurn!==undefined)(u as Unit).aiTTurn=int(s.groups.Unit.aiTTurn);
if(s.groups.Unit.aiPlav!==undefined)(u as Unit).aiPlav=int(s.groups.Unit.aiPlav);
if(s.groups.Unit.aiState!==undefined)(u as Unit).aiState=int(s.groups.Unit.aiState);
if(s.groups.Unit.aiTCh!==undefined)(u as Unit).aiTCh=int(s.groups.Unit.aiTCh);
if(s.groups.Unit.aiSpok!==undefined)(u as Unit).aiSpok=int(s.groups.Unit.aiSpok);
if(s.groups.Unit.maxSpok!==undefined)(u as Unit).maxSpok=int(s.groups.Unit.maxSpok);
if(s.groups.Unit.timerDie!==undefined)(u as Unit).timerDie=int(s.groups.Unit.timerDie);
if(s.groups.Unit.t_hitPart!==undefined)(u as Unit).t_hitPart=int(s.groups.Unit.t_hitPart);
if(s.groups.Unit.hitSumm!==undefined)(u as Unit).hitSumm=Number(s.groups.Unit.hitSumm);
if(s.groups.Unit.t_mess!==undefined)(u as Unit).t_mess=int(s.groups.Unit.t_mess);
if(s.groups.Unit.kolChild!==undefined)(u as Unit).kolChild=int(s.groups.Unit.kolChild);
}
if(u is UnitAIRobot && s.groups.UnitAIRobot!=null) {
if(s.groups.UnitAIRobot.weap!==undefined)(u as UnitAIRobot).weap=String(s.groups.UnitAIRobot.weap);
if(s.groups.UnitAIRobot.isPort!==undefined)(u as UnitAIRobot).isPort=Boolean(s.groups.UnitAIRobot.isPort);
if(s.groups.UnitAIRobot.t_port!==undefined)(u as UnitAIRobot).t_port=int(s.groups.UnitAIRobot.t_port);
if(s.groups.UnitAIRobot.kol_port!==undefined)(u as UnitAIRobot).kol_port=int(s.groups.UnitAIRobot.kol_port);
if(s.groups.UnitAIRobot.aiAttackT!==undefined)(u as UnitAIRobot).aiAttackT=int(s.groups.UnitAIRobot.aiAttackT);
if(s.groups.UnitAIRobot.aiAttackOch!==undefined)(u as UnitAIRobot).aiAttackOch=int(s.groups.UnitAIRobot.aiAttackOch);
if(s.groups.UnitAIRobot.aiDist!==undefined)(u as UnitAIRobot).aiDist=int(s.groups.UnitAIRobot.aiDist);
}
if(u is UnitAlicorn && s.groups.UnitAlicorn!=null) {
if(s.groups.UnitAlicorn.floatX!==undefined)(u as UnitAlicorn).floatX=Number(s.groups.UnitAlicorn.floatX);
if(s.groups.UnitAlicorn.floatY!==undefined)(u as UnitAlicorn).floatY=Number(s.groups.UnitAlicorn.floatY);
if(s.groups.UnitAlicorn.shitMaxHp!==undefined)(u as UnitAlicorn).shitMaxHp=Number(s.groups.UnitAlicorn.shitMaxHp);
if(s.groups.UnitAlicorn.superSilaTip!==undefined)(u as UnitAlicorn).superSilaTip=int(s.groups.UnitAlicorn.superSilaTip);
if(s.groups.UnitAlicorn.tGotov!==undefined)(u as UnitAlicorn).tGotov=int(s.groups.UnitAlicorn.tGotov);
if(s.groups.UnitAlicorn.tUsed!==undefined)(u as UnitAlicorn).tUsed=int(s.groups.UnitAlicorn.tUsed);
if(s.groups.UnitAlicorn.tSuper!==undefined)(u as UnitAlicorn).tSuper=int(s.groups.UnitAlicorn.tSuper);
if(s.groups.UnitAlicorn.tNomater!==undefined)(u as UnitAlicorn).tNomater=int(s.groups.UnitAlicorn.tNomater);
if(s.groups.UnitAlicorn.superInvis!==undefined)(u as UnitAlicorn).superInvis=Boolean(s.groups.UnitAlicorn.superInvis);
if(s.groups.UnitAlicorn.curA!==undefined)(u as UnitAlicorn).curA=int(s.groups.UnitAlicorn.curA);
if(s.groups.UnitAlicorn.celA!==undefined)(u as UnitAlicorn).celA=int(s.groups.UnitAlicorn.celA);
if(s.groups.UnitAlicorn.tTeleThrow!==undefined)(u as UnitAlicorn).tTeleThrow=int(s.groups.UnitAlicorn.tTeleThrow);
if(s.groups.UnitAlicorn.tTeleRes!==undefined)(u as UnitAlicorn).tTeleRes=int(s.groups.UnitAlicorn.tTeleRes);
if(s.groups.UnitAlicorn.throwForce!==undefined)(u as UnitAlicorn).throwForce=Number(s.groups.UnitAlicorn.throwForce);
if(s.groups.UnitAlicorn.teleX!==undefined)(u as UnitAlicorn).teleX=Number(s.groups.UnitAlicorn.teleX);
if(s.groups.UnitAlicorn.teleY!==undefined)(u as UnitAlicorn).teleY=Number(s.groups.UnitAlicorn.teleY);
if(s.groups.UnitAlicorn.teleSpeed!==undefined)(u as UnitAlicorn).teleSpeed=Number(s.groups.UnitAlicorn.teleSpeed);
if(s.groups.UnitAlicorn.teleAccel!==undefined)(u as UnitAlicorn).teleAccel=Number(s.groups.UnitAlicorn.teleAccel);
if(s.groups.UnitAlicorn.derp!==undefined)(u as UnitAlicorn).derp=Number(s.groups.UnitAlicorn.derp);
if(s.groups.UnitAlicorn.tlColor!==undefined)(u as UnitAlicorn).tlColor=uint(s.groups.UnitAlicorn.tlColor);
if(s.groups.UnitAlicorn.nmColor!==undefined)(u as UnitAlicorn).nmColor=uint(s.groups.UnitAlicorn.nmColor);
if(s.groups.UnitAlicorn.blasted!==undefined)(u as UnitAlicorn).blasted=Boolean(s.groups.UnitAlicorn.blasted);
if(s.groups.UnitAlicorn.osob!==undefined)(u as UnitAlicorn).osob=Boolean(s.groups.UnitAlicorn.osob);
if(s.groups.UnitAlicorn.t_pole!==undefined)(u as UnitAlicorn).t_pole=int(s.groups.UnitAlicorn.t_pole);
if(s.groups.UnitAlicorn.optDistAtt!==undefined)(u as UnitAlicorn).optDistAtt=int(s.groups.UnitAlicorn.optDistAtt);
if(s.groups.UnitAlicorn.optDistTele!==undefined)(u as UnitAlicorn).optDistTele=int(s.groups.UnitAlicorn.optDistTele);
if(s.groups.UnitAlicorn.stalkDist!==undefined)(u as UnitAlicorn).stalkDist=int(s.groups.UnitAlicorn.stalkDist);
if(s.groups.UnitAlicorn.aiAttackT!==undefined)(u as UnitAlicorn).aiAttackT=int(s.groups.UnitAlicorn.aiAttackT);
if(s.groups.UnitAlicorn.t_landing!==undefined)(u as UnitAlicorn).t_landing=int(s.groups.UnitAlicorn.t_landing);
if(s.groups.UnitAlicorn.t_float!==undefined)(u as UnitAlicorn).t_float=Number(s.groups.UnitAlicorn.t_float);
if(s.groups.UnitAlicorn.t_fall!==undefined)(u as UnitAlicorn).t_fall=int(s.groups.UnitAlicorn.t_fall);
if(s.groups.UnitAlicorn.t_nomater!==undefined)(u as UnitAlicorn).t_nomater=int(s.groups.UnitAlicorn.t_nomater);
if(s.groups.UnitAlicorn.t_shit!==undefined)(u as UnitAlicorn).t_shit=int(s.groups.UnitAlicorn.t_shit);
if(s.groups.UnitAlicorn.t_gotov!==undefined)(u as UnitAlicorn).t_gotov=int(s.groups.UnitAlicorn.t_gotov);
if(s.groups.UnitAlicorn.t_super!==undefined)(u as UnitAlicorn).t_super=int(s.groups.UnitAlicorn.t_super);
if(s.groups.UnitAlicorn.t_tele!==undefined)(u as UnitAlicorn).t_tele=int(s.groups.UnitAlicorn.t_tele);
if(s.groups.UnitAlicorn.t_alarm!==undefined)(u as UnitAlicorn).t_alarm=int(s.groups.UnitAlicorn.t_alarm);
}
if(u is UnitAnt && s.groups.UnitAnt!=null) {
if(s.groups.UnitAnt.optDistAtt!==undefined)(u as UnitAnt).optDistAtt=int(s.groups.UnitAnt.optDistAtt);
if(s.groups.UnitAnt.optJumping!==undefined)(u as UnitAnt).optJumping=Boolean(s.groups.UnitAnt.optJumping);
if(s.groups.UnitAnt.optJumpAtt!==undefined)(u as UnitAnt).optJumpAtt=Boolean(s.groups.UnitAnt.optJumpAtt);
if(s.groups.UnitAnt.optAnimAtt!==undefined)(u as UnitAnt).optAnimAtt=Boolean(s.groups.UnitAnt.optAnimAtt);
if(s.groups.UnitAnt.t_punch!==undefined)(u as UnitAnt).t_punch=int(s.groups.UnitAnt.t_punch);
if(s.groups.UnitAnt.vstorona!==undefined)(u as UnitAnt).vstorona=int(s.groups.UnitAnt.vstorona);
if(s.groups.UnitAnt.aiLaz!==undefined)(u as UnitAnt).aiLaz=int(s.groups.UnitAnt.aiLaz);
if(s.groups.UnitAnt.aiNeedLaz!==undefined)(u as UnitAnt).aiNeedLaz=int(s.groups.UnitAnt.aiNeedLaz);
}
if(u is UnitBat && s.groups.UnitBat!=null) {
if(s.groups.UnitBat.tr!==undefined)(u as UnitBat).tr=int(s.groups.UnitBat.tr);
if(s.groups.UnitBat.aiDx!==undefined)(u as UnitBat).aiDx=Number(s.groups.UnitBat.aiDx);
if(s.groups.UnitBat.aiDy!==undefined)(u as UnitBat).aiDy=Number(s.groups.UnitBat.aiDy);
if(s.groups.UnitBat.aiRasst!==undefined)(u as UnitBat).aiRasst=Number(s.groups.UnitBat.aiRasst);
}
if(u is UnitBloat && s.groups.UnitBloat!=null) {
if(s.groups.UnitBloat.cDam!==undefined)(u as UnitBloat).cDam=Number(s.groups.UnitBloat.cDam);
if(s.groups.UnitBloat.isEmit!==undefined)(u as UnitBloat).isEmit=Boolean(s.groups.UnitBloat.isEmit);
if(s.groups.UnitBloat.gryz!==undefined)(u as UnitBloat).gryz=Boolean(s.groups.UnitBloat.gryz);
if(s.groups.UnitBloat.isGryz!==undefined)(u as UnitBloat).isGryz=Boolean(s.groups.UnitBloat.isGryz);
if(s.groups.UnitBloat.shootCh!==undefined)(u as UnitBloat).shootCh=Number(s.groups.UnitBloat.shootCh);
if(s.groups.UnitBloat.aiDx!==undefined)(u as UnitBloat).aiDx=Number(s.groups.UnitBloat.aiDx);
if(s.groups.UnitBloat.aiDy!==undefined)(u as UnitBloat).aiDy=Number(s.groups.UnitBloat.aiDy);
if(s.groups.UnitBloat.aiRasst!==undefined)(u as UnitBloat).aiRasst=Number(s.groups.UnitBloat.aiRasst);
if(s.groups.UnitBloat.attRasst!==undefined)(u as UnitBloat).attRasst=int(s.groups.UnitBloat.attRasst);
if(s.groups.UnitBloat.attCh!==undefined)(u as UnitBloat).attCh=Number(s.groups.UnitBloat.attCh);
}
if(u is UnitBloatEmitter && s.groups.UnitBloatEmitter!=null) {
if(s.groups.UnitBloatEmitter.emitId!==undefined)(u as UnitBloatEmitter).emitId=String(s.groups.UnitBloatEmitter.emitId);
if(s.groups.UnitBloatEmitter.emit_t!==undefined)(u as UnitBloatEmitter).emit_t=int(s.groups.UnitBloatEmitter.emit_t);
}
if(u is UnitBossAlicorn && s.groups.UnitBossAlicorn!=null) {
if(s.groups.UnitBossAlicorn.weap!==undefined)(u as UnitBossAlicorn).weap=String(s.groups.UnitBossAlicorn.weap);
if(s.groups.UnitBossAlicorn.shitMaxHp!==undefined)(u as UnitBossAlicorn).shitMaxHp=Number(s.groups.UnitBossAlicorn.shitMaxHp);
if(s.groups.UnitBossAlicorn.isShit!==undefined)(u as UnitBossAlicorn).isShit=Boolean(s.groups.UnitBossAlicorn.isShit);
if(s.groups.UnitBossAlicorn.isBlast!==undefined)(u as UnitBossAlicorn).isBlast=Boolean(s.groups.UnitBossAlicorn.isBlast);
if(s.groups.UnitBossAlicorn.t_float!==undefined)(u as UnitBossAlicorn).t_float=Number(s.groups.UnitBossAlicorn.t_float);
if(s.groups.UnitBossAlicorn.floatX!==undefined)(u as UnitBossAlicorn).floatX=Number(s.groups.UnitBossAlicorn.floatX);
if(s.groups.UnitBossAlicorn.floatY!==undefined)(u as UnitBossAlicorn).floatY=Number(s.groups.UnitBossAlicorn.floatY);
if(s.groups.UnitBossAlicorn.throwForce!==undefined)(u as UnitBossAlicorn).throwForce=Number(s.groups.UnitBossAlicorn.throwForce);
if(s.groups.UnitBossAlicorn.teleX!==undefined)(u as UnitBossAlicorn).teleX=Number(s.groups.UnitBossAlicorn.teleX);
if(s.groups.UnitBossAlicorn.teleY!==undefined)(u as UnitBossAlicorn).teleY=Number(s.groups.UnitBossAlicorn.teleY);
if(s.groups.UnitBossAlicorn.teleSpeed!==undefined)(u as UnitBossAlicorn).teleSpeed=Number(s.groups.UnitBossAlicorn.teleSpeed);
if(s.groups.UnitBossAlicorn.teleAccel!==undefined)(u as UnitBossAlicorn).teleAccel=Number(s.groups.UnitBossAlicorn.teleAccel);
if(s.groups.UnitBossAlicorn.derp!==undefined)(u as UnitBossAlicorn).derp=Number(s.groups.UnitBossAlicorn.derp);
if(s.groups.UnitBossAlicorn.optDistTele!==undefined)(u as UnitBossAlicorn).optDistTele=int(s.groups.UnitBossAlicorn.optDistTele);
if(s.groups.UnitBossAlicorn.superInvis!==undefined)(u as UnitBossAlicorn).superInvis=Boolean(s.groups.UnitBossAlicorn.superInvis);
if(s.groups.UnitBossAlicorn.curA!==undefined)(u as UnitBossAlicorn).curA=int(s.groups.UnitBossAlicorn.curA);
if(s.groups.UnitBossAlicorn.celA!==undefined)(u as UnitBossAlicorn).celA=int(s.groups.UnitBossAlicorn.celA);
if(s.groups.UnitBossAlicorn.emit_t!==undefined)(u as UnitBossAlicorn).emit_t=int(s.groups.UnitBossAlicorn.emit_t);
if(s.groups.UnitBossAlicorn.moveX!==undefined)(u as UnitBossAlicorn).moveX=Number(s.groups.UnitBossAlicorn.moveX);
if(s.groups.UnitBossAlicorn.moveY!==undefined)(u as UnitBossAlicorn).moveY=Number(s.groups.UnitBossAlicorn.moveY);
if(s.groups.UnitBossAlicorn.attState!==undefined)(u as UnitBossAlicorn).attState=int(s.groups.UnitBossAlicorn.attState);
if(s.groups.UnitBossAlicorn.t_turn!==undefined)(u as UnitBossAlicorn).t_turn=int(s.groups.UnitBossAlicorn.t_turn);
if(s.groups.UnitBossAlicorn.t_shit!==undefined)(u as UnitBossAlicorn).t_shit=int(s.groups.UnitBossAlicorn.t_shit);
if(s.groups.UnitBossAlicorn.t_fly!==undefined)(u as UnitBossAlicorn).t_fly=int(s.groups.UnitBossAlicorn.t_fly);
}
if(u is UnitBossDron && s.groups.UnitBossDron!=null) {
if(s.groups.UnitBossDron.shitMaxHp!==undefined)(u as UnitBossDron).shitMaxHp=Number(s.groups.UnitBossDron.shitMaxHp);
if(s.groups.UnitBossDron.emit_t!==undefined)(u as UnitBossDron).emit_t=int(s.groups.UnitBossDron.emit_t);
if(s.groups.UnitBossDron.moveX!==undefined)(u as UnitBossDron).moveX=Number(s.groups.UnitBossDron.moveX);
if(s.groups.UnitBossDron.moveY!==undefined)(u as UnitBossDron).moveY=Number(s.groups.UnitBossDron.moveY);
if(s.groups.UnitBossDron.t_atk!==undefined)(u as UnitBossDron).t_atk=int(s.groups.UnitBossDron.t_atk);
if(s.groups.UnitBossDron.t_shit!==undefined)(u as UnitBossDron).t_shit=int(s.groups.UnitBossDron.t_shit);
if(s.groups.UnitBossDron.kolth!==undefined)(u as UnitBossDron).kolth=int(s.groups.UnitBossDron.kolth);
if(s.groups.UnitBossDron.speedBonus!==undefined)(u as UnitBossDron).speedBonus=Number(s.groups.UnitBossDron.speedBonus);
}
if(u is UnitBossEncl && s.groups.UnitBossEncl!=null) {
if(s.groups.UnitBossEncl.weap!==undefined)(u as UnitBossEncl).weap=String(s.groups.UnitBossEncl.weap);
if(s.groups.UnitBossEncl.minY!==undefined)(u as UnitBossEncl).minY=int(s.groups.UnitBossEncl.minY);
if(s.groups.UnitBossEncl.maxY!==undefined)(u as UnitBossEncl).maxY=int(s.groups.UnitBossEncl.maxY);
if(s.groups.UnitBossEncl.minX!==undefined)(u as UnitBossEncl).minX=int(s.groups.UnitBossEncl.minX);
if(s.groups.UnitBossEncl.maxX!==undefined)(u as UnitBossEncl).maxX=int(s.groups.UnitBossEncl.maxX);
if(s.groups.UnitBossEncl.sinX!==undefined)(u as UnitBossEncl).sinX=Number(s.groups.UnitBossEncl.sinX);
if(s.groups.UnitBossEncl.sinDX!==undefined)(u as UnitBossEncl).sinDX=Number(s.groups.UnitBossEncl.sinDX);
if(s.groups.UnitBossEncl.emit_t!==undefined)(u as UnitBossEncl).emit_t=int(s.groups.UnitBossEncl.emit_t);
}
if(u is UnitBossNecr && s.groups.UnitBossNecr!=null) {
if(s.groups.UnitBossNecr.atk_t!==undefined)(u as UnitBossNecr).atk_t=int(s.groups.UnitBossNecr.atk_t);
if(s.groups.UnitBossNecr.throu_t!==undefined)(u as UnitBossNecr).throu_t=int(s.groups.UnitBossNecr.throu_t);
if(s.groups.UnitBossNecr.atk_n!==undefined)(u as UnitBossNecr).atk_n=int(s.groups.UnitBossNecr.atk_n);
if(s.groups.UnitBossNecr.prot_n!==undefined)(u as UnitBossNecr).prot_n=int(s.groups.UnitBossNecr.prot_n);
if(s.groups.UnitBossNecr.protculd_t!==undefined)(u as UnitBossNecr).protculd_t=int(s.groups.UnitBossNecr.protculd_t);
if(s.groups.UnitBossNecr.curseculd_t!==undefined)(u as UnitBossNecr).curseculd_t=int(s.groups.UnitBossNecr.curseculd_t);
if(s.groups.UnitBossNecr.prot_t!==undefined)(u as UnitBossNecr).prot_t=int(s.groups.UnitBossNecr.prot_t);
if(s.groups.UnitBossNecr.healHp!==undefined)(u as UnitBossNecr).healHp=Number(s.groups.UnitBossNecr.healHp);
if(s.groups.UnitBossNecr.isShadow!==undefined)(u as UnitBossNecr).isShadow=Boolean(s.groups.UnitBossNecr.isShadow);
if(s.groups.UnitBossNecr.superInvis!==undefined)(u as UnitBossNecr).superInvis=Boolean(s.groups.UnitBossNecr.superInvis);
if(s.groups.UnitBossNecr.curA!==undefined)(u as UnitBossNecr).curA=int(s.groups.UnitBossNecr.curA);
if(s.groups.UnitBossNecr.celA!==undefined)(u as UnitBossNecr).celA=int(s.groups.UnitBossNecr.celA);
}
if(u is UnitBossRaider && s.groups.UnitBossRaider!=null) {
if(s.groups.UnitBossRaider.weap!==undefined)(u as UnitBossRaider).weap=String(s.groups.UnitBossRaider.weap);
if(s.groups.UnitBossRaider.aiLaz!==undefined)(u as UnitBossRaider).aiLaz=int(s.groups.UnitBossRaider.aiLaz);
if(s.groups.UnitBossRaider.aiJump!==undefined)(u as UnitBossRaider).aiJump=int(s.groups.UnitBossRaider.aiJump);
if(s.groups.UnitBossRaider.aiAttack!==undefined)(u as UnitBossRaider).aiAttack=int(s.groups.UnitBossRaider.aiAttack);
if(s.groups.UnitBossRaider.attackerType!==undefined)(u as UnitBossRaider).attackerType=int(s.groups.UnitBossRaider.attackerType);
if(s.groups.UnitBossRaider.aiAttackT!==undefined)(u as UnitBossRaider).aiAttackT=int(s.groups.UnitBossRaider.aiAttackT);
if(s.groups.UnitBossRaider.aiAttackOch!==undefined)(u as UnitBossRaider).aiAttackOch=int(s.groups.UnitBossRaider.aiAttackOch);
if(s.groups.UnitBossRaider.aiDist!==undefined)(u as UnitBossRaider).aiDist=int(s.groups.UnitBossRaider.aiDist);
if(s.groups.UnitBossRaider.aiVKurse!==undefined)(u as UnitBossRaider).aiVKurse=Boolean(s.groups.UnitBossRaider.aiVKurse);
if(s.groups.UnitBossRaider.t_chCel!==undefined)(u as UnitBossRaider).t_chCel=int(s.groups.UnitBossRaider.t_chCel);
if(s.groups.UnitBossRaider.emit_t!==undefined)(u as UnitBossRaider).emit_t=int(s.groups.UnitBossRaider.emit_t);
}
if(u is UnitBossUltra && s.groups.UnitBossUltra!=null) {
if(s.groups.UnitBossUltra.weap!==undefined)(u as UnitBossUltra).weap=String(s.groups.UnitBossUltra.weap);
if(s.groups.UnitBossUltra.shitMaxHp!==undefined)(u as UnitBossUltra).shitMaxHp=Number(s.groups.UnitBossUltra.shitMaxHp);
if(s.groups.UnitBossUltra.usil!==undefined)(u as UnitBossUltra).usil=Boolean(s.groups.UnitBossUltra.usil);
if(s.groups.UnitBossUltra.emit_t!==undefined)(u as UnitBossUltra).emit_t=int(s.groups.UnitBossUltra.emit_t);
if(s.groups.UnitBossUltra.moveX!==undefined)(u as UnitBossUltra).moveX=Number(s.groups.UnitBossUltra.moveX);
if(s.groups.UnitBossUltra.moveY!==undefined)(u as UnitBossUltra).moveY=Number(s.groups.UnitBossUltra.moveY);
if(s.groups.UnitBossUltra.attState!==undefined)(u as UnitBossUltra).attState=int(s.groups.UnitBossUltra.attState);
if(s.groups.UnitBossUltra.t_turn!==undefined)(u as UnitBossUltra).t_turn=int(s.groups.UnitBossUltra.t_turn);
if(s.groups.UnitBossUltra.t_shit!==undefined)(u as UnitBossUltra).t_shit=int(s.groups.UnitBossUltra.t_shit);
}
if(u is UnitCaptive && s.groups.UnitCaptive!=null) {
if(s.groups.UnitCaptive.tr!==undefined)(u as UnitCaptive).tr=int(s.groups.UnitCaptive.tr);
if(s.groups.UnitCaptive.sr!==undefined)(u as UnitCaptive).sr=int(s.groups.UnitCaptive.sr);
if(s.groups.UnitCaptive.novoi!==undefined)(u as UnitCaptive).novoi=Boolean(s.groups.UnitCaptive.novoi);
}
if(u is UnitDamager && s.groups.UnitDamager!=null) {
if(s.groups.UnitDamager.tr!==undefined)(u as UnitDamager).tr=String(s.groups.UnitDamager.tr);
if(s.groups.UnitDamager.weap!==undefined)(u as UnitDamager).weap=String(s.groups.UnitDamager.weap);
if(s.groups.UnitDamager.tipDamager!==undefined)(u as UnitDamager).tipDamager=int(s.groups.UnitDamager.tipDamager);
if(s.groups.UnitDamager.status!==undefined)(u as UnitDamager).status=int(s.groups.UnitDamager.status);
if(s.groups.UnitDamager.needSkill!==undefined)(u as UnitDamager).needSkill=String(s.groups.UnitDamager.needSkill);
if(s.groups.UnitDamager.isAct!==undefined)(u as UnitDamager).isAct=Boolean(s.groups.UnitDamager.isAct);
if(s.groups.UnitDamager.allid!==undefined)(u as UnitDamager).allid=String(s.groups.UnitDamager.allid);
if(s.groups.UnitDamager.och!==undefined)(u as UnitDamager).och=int(s.groups.UnitDamager.och);
if(s.groups.UnitDamager.noch!==undefined)(u as UnitDamager).noch=int(s.groups.UnitDamager.noch);
if(s.groups.UnitDamager.kolammo!==undefined)(u as UnitDamager).kolammo=int(s.groups.UnitDamager.kolammo);
if(s.groups.UnitDamager.damageExpl!==undefined)(u as UnitDamager).damageExpl=Number(s.groups.UnitDamager.damageExpl);
if(s.groups.UnitDamager.destroyExpl!==undefined)(u as UnitDamager).destroyExpl=Number(s.groups.UnitDamager.destroyExpl);
if(s.groups.UnitDamager.explRadius!==undefined)(u as UnitDamager).explRadius=Number(s.groups.UnitDamager.explRadius);
if(s.groups.UnitDamager.aiN!==undefined)(u as UnitDamager).aiN=int(s.groups.UnitDamager.aiN);
}
if(u is UnitDestr && s.groups.UnitDestr!=null) {
if(s.groups.UnitDestr.tr!==undefined)(u as UnitDestr).tr=int(s.groups.UnitDestr.tr);
if(s.groups.UnitDestr.t_part!==undefined)(u as UnitDestr).t_part=int(s.groups.UnitDestr.t_part);
}
if(u is UnitDron && s.groups.UnitDron!=null) {
if(s.groups.UnitDron.br!==undefined)(u as UnitDron).br=Number(s.groups.UnitDron.br);
if(s.groups.UnitDron.stuk!==undefined)(u as UnitDron).stuk=int(s.groups.UnitDron.stuk);
if(s.groups.UnitDron.weap!==undefined)(u as UnitDron).weap=String(s.groups.UnitDron.weap);
if(s.groups.UnitDron.atkDist!==undefined)(u as UnitDron).atkDist=Number(s.groups.UnitDron.atkDist);
if(s.groups.UnitDron.aiAgr!==undefined)(u as UnitDron).aiAgr=Boolean(s.groups.UnitDron.aiAgr);
if(s.groups.UnitDron.floatX!==undefined)(u as UnitDron).floatX=Number(s.groups.UnitDron.floatX);
if(s.groups.UnitDron.floatY!==undefined)(u as UnitDron).floatY=Number(s.groups.UnitDron.floatY);
if(s.groups.UnitDron.t_float!==undefined)(u as UnitDron).t_float=Number(s.groups.UnitDron.t_float);
if(s.groups.UnitDron.atkRasst!==undefined)(u as UnitDron).atkRasst=Number(s.groups.UnitDron.atkRasst);
if(s.groups.UnitDron.t_krut!==undefined)(u as UnitDron).t_krut=int(s.groups.UnitDron.t_krut);
}
if(u is UnitEncl && s.groups.UnitEncl!=null) {
if(s.groups.UnitEncl.t_gren!==undefined)(u as UnitEncl).t_gren=int(s.groups.UnitEncl.t_gren);
}
if(u is UnitEqd && s.groups.UnitEqd!=null) {
if(s.groups.UnitEqd.jump_n!==undefined)(u as UnitEqd).jump_n=int(s.groups.UnitEqd.jump_n);
}
if(u is UnitFish && s.groups.UnitFish!=null) {
if(s.groups.UnitFish.aiDx!==undefined)(u as UnitFish).aiDx=Number(s.groups.UnitFish.aiDx);
if(s.groups.UnitFish.aiDy!==undefined)(u as UnitFish).aiDy=Number(s.groups.UnitFish.aiDy);
if(s.groups.UnitFish.aiRasst!==undefined)(u as UnitFish).aiRasst=Number(s.groups.UnitFish.aiRasst);
}
if(u is UnitHellhound && s.groups.UnitHellhound!=null) {
if(s.groups.UnitHellhound.vDestroy!==undefined)(u as UnitHellhound).vDestroy=Number(s.groups.UnitHellhound.vDestroy);
if(s.groups.UnitHellhound.nuh!==undefined)(u as UnitHellhound).nuh=Number(s.groups.UnitHellhound.nuh);
if(s.groups.UnitHellhound.aiJump!==undefined)(u as UnitHellhound).aiJump=int(s.groups.UnitHellhound.aiJump);
if(s.groups.UnitHellhound.aiLaz!==undefined)(u as UnitHellhound).aiLaz=int(s.groups.UnitHellhound.aiLaz);
if(s.groups.UnitHellhound.t_laz!==undefined)(u as UnitHellhound).t_laz=int(s.groups.UnitHellhound.t_laz);
if(s.groups.UnitHellhound.r_laz!==undefined)(u as UnitHellhound).r_laz=int(s.groups.UnitHellhound.r_laz);
}
if(u is UnitMerc && s.groups.UnitMerc!=null) {
if(s.groups.UnitMerc.t_gren!==undefined)(u as UnitMerc).t_gren=int(s.groups.UnitMerc.t_gren);
}
if(u is UnitMonstrik && s.groups.UnitMonstrik!=null) {
if(s.groups.UnitMonstrik.optDistAtt!==undefined)(u as UnitMonstrik).optDistAtt=int(s.groups.UnitMonstrik.optDistAtt);
if(s.groups.UnitMonstrik.optJumping!==undefined)(u as UnitMonstrik).optJumping=Boolean(s.groups.UnitMonstrik.optJumping);
if(s.groups.UnitMonstrik.optJumpAtt!==undefined)(u as UnitMonstrik).optJumpAtt=Boolean(s.groups.UnitMonstrik.optJumpAtt);
if(s.groups.UnitMonstrik.optAnimAtt!==undefined)(u as UnitMonstrik).optAnimAtt=Boolean(s.groups.UnitMonstrik.optAnimAtt);
if(s.groups.UnitMonstrik.t_punch!==undefined)(u as UnitMonstrik).t_punch=int(s.groups.UnitMonstrik.t_punch);
}
if(u is UnitMsp && s.groups.UnitMsp!=null) {
if(s.groups.UnitMsp.weap!==undefined)(u as UnitMsp).weap=String(s.groups.UnitMsp.weap);
if(s.groups.UnitMsp.cep!==undefined)(u as UnitMsp).cep=int(s.groups.UnitMsp.cep);
}
if(u is UnitMWall && s.groups.UnitMWall!=null) {
if(s.groups.UnitMWall.rearm!==undefined)(u as UnitMWall).rearm=Boolean(s.groups.UnitMWall.rearm);
}
if(u is UnitNecros && s.groups.UnitNecros!=null) {
if(s.groups.UnitNecros.br!==undefined)(u as UnitNecros).br=Number(s.groups.UnitNecros.br);
}
if(u is UnitNPC && s.groups.UnitNPC!=null) {
if(s.groups.UnitNPC.t_ref!==undefined)(u as UnitNPC).t_ref=int(s.groups.UnitNPC.t_ref);
if(s.groups.UnitNPC.t_anim!==undefined)(u as UnitNPC).t_anim=int(s.groups.UnitNPC.t_anim);
if(s.groups.UnitNPC.t_float!==undefined)(u as UnitNPC).t_float=Number(s.groups.UnitNPC.t_float);
if(s.groups.UnitNPC.floatX!==undefined)(u as UnitNPC).floatX=Number(s.groups.UnitNPC.floatX);
if(s.groups.UnitNPC.floatY!==undefined)(u as UnitNPC).floatY=Number(s.groups.UnitNPC.floatY);
if(s.groups.UnitNPC.wait!==undefined)(u as UnitNPC).wait=int(s.groups.UnitNPC.wait);
if(s.groups.UnitNPC.dey!==undefined)(u as UnitNPC).dey=String(s.groups.UnitNPC.dey);
if(s.groups.UnitNPC.cx!==undefined)(u as UnitNPC).cx=Number(s.groups.UnitNPC.cx);
if(s.groups.UnitNPC.cy!==undefined)(u as UnitNPC).cy=Number(s.groups.UnitNPC.cy);
}
if(u is UnitPhoenix && s.groups.UnitPhoenix!=null) {
if(s.groups.UnitPhoenix.t_fall!==undefined)(u as UnitPhoenix).t_fall=int(s.groups.UnitPhoenix.t_fall);
}
if(u is UnitPonPon && s.groups.UnitPonPon!=null) {
if(s.groups.UnitPonPon.tr!==undefined)(u as UnitPonPon).tr=int(s.groups.UnitPonPon.tr);
if(s.groups.UnitPonPon.act!==undefined)(u as UnitPonPon).act=Boolean(s.groups.UnitPonPon.act);
if(s.groups.UnitPonPon.novoi!==undefined)(u as UnitPonPon).novoi=Boolean(s.groups.UnitPonPon.novoi);
if(s.groups.UnitPonPon.verVis!==undefined)(u as UnitPonPon).verVis=Number(s.groups.UnitPonPon.verVis);
if(s.groups.UnitPonPon.privet!==undefined)(u as UnitPonPon).privet=Boolean(s.groups.UnitPonPon.privet);
}
if(u is UnitProtect && s.groups.UnitProtect!=null) {
if(s.groups.UnitProtect.jump_n!==undefined)(u as UnitProtect).jump_n=int(s.groups.UnitProtect.jump_n);
if(s.groups.UnitProtect.jump_m!==undefined)(u as UnitProtect).jump_m=int(s.groups.UnitProtect.jump_m);
}
if(u is UnitRaider && s.groups.UnitRaider!=null) {
if(s.groups.UnitRaider.weap!==undefined)(u as UnitRaider).weap=String(s.groups.UnitRaider.weap);
if(s.groups.UnitRaider.visionMult!==undefined)(u as UnitRaider).visionMult=Number(s.groups.UnitRaider.visionMult);
if(s.groups.UnitRaider.baseDexter!==undefined)(u as UnitRaider).baseDexter=Number(s.groups.UnitRaider.baseDexter);
if(s.groups.UnitRaider.floatX!==undefined)(u as UnitRaider).floatX=Number(s.groups.UnitRaider.floatX);
if(s.groups.UnitRaider.floatY!==undefined)(u as UnitRaider).floatY=Number(s.groups.UnitRaider.floatY);
if(s.groups.UnitRaider.aiLaz!==undefined)(u as UnitRaider).aiLaz=int(s.groups.UnitRaider.aiLaz);
if(s.groups.UnitRaider.aiJump!==undefined)(u as UnitRaider).aiJump=int(s.groups.UnitRaider.aiJump);
if(s.groups.UnitRaider.aiAttack!==undefined)(u as UnitRaider).aiAttack=int(s.groups.UnitRaider.aiAttack);
if(s.groups.UnitRaider.attackerType!==undefined)(u as UnitRaider).attackerType=int(s.groups.UnitRaider.attackerType);
if(s.groups.UnitRaider.aiAttackT!==undefined)(u as UnitRaider).aiAttackT=int(s.groups.UnitRaider.aiAttackT);
if(s.groups.UnitRaider.aiAttackOch!==undefined)(u as UnitRaider).aiAttackOch=int(s.groups.UnitRaider.aiAttackOch);
if(s.groups.UnitRaider.aiDist!==undefined)(u as UnitRaider).aiDist=int(s.groups.UnitRaider.aiDist);
if(s.groups.UnitRaider.stalkDist!==undefined)(u as UnitRaider).stalkDist=int(s.groups.UnitRaider.stalkDist);
if(s.groups.UnitRaider.aiVKurse!==undefined)(u as UnitRaider).aiVKurse=Boolean(s.groups.UnitRaider.aiVKurse);
if(s.groups.UnitRaider.t_chCel!==undefined)(u as UnitRaider).t_chCel=int(s.groups.UnitRaider.t_chCel);
if(s.groups.UnitRaider.emit_t!==undefined)(u as UnitRaider).emit_t=int(s.groups.UnitRaider.emit_t);
if(s.groups.UnitRaider.t_laz!==undefined)(u as UnitRaider).t_laz=int(s.groups.UnitRaider.t_laz);
if(s.groups.UnitRaider.r_laz!==undefined)(u as UnitRaider).r_laz=int(s.groups.UnitRaider.r_laz);
if(s.groups.UnitRaider.t_landing!==undefined)(u as UnitRaider).t_landing=int(s.groups.UnitRaider.t_landing);
if(s.groups.UnitRaider.t_float!==undefined)(u as UnitRaider).t_float=Number(s.groups.UnitRaider.t_float);
if(s.groups.UnitRaider.t_fall!==undefined)(u as UnitRaider).t_fall=int(s.groups.UnitRaider.t_fall);
if(s.groups.UnitRaider.t_turn!==undefined)(u as UnitRaider).t_turn=int(s.groups.UnitRaider.t_turn);
if(s.groups.UnitRaider.tstor!==undefined)(u as UnitRaider).tstor=int(s.groups.UnitRaider.tstor);
if(s.groups.UnitRaider.plusObservOk!==undefined)(u as UnitRaider).plusObservOk=Boolean(s.groups.UnitRaider.plusObservOk);
if(s.groups.UnitRaider.plusObserv!==undefined)(u as UnitRaider).plusObserv=int(s.groups.UnitRaider.plusObserv);
}
if(u is UnitRanger && s.groups.UnitRanger!=null) {
if(s.groups.UnitRanger.t_gren!==undefined)(u as UnitRanger).t_gren=int(s.groups.UnitRanger.t_gren);
}
if(u is UnitRoller && s.groups.UnitRoller!=null) {
if(s.groups.UnitRoller.rollDr!==undefined)(u as UnitRoller).rollDr=Number(s.groups.UnitRoller.rollDr);
if(s.groups.UnitRoller.tr!==undefined)(u as UnitRoller).tr=int(s.groups.UnitRoller.tr);
if(s.groups.UnitRoller.optDistAtt!==undefined)(u as UnitRoller).optDistAtt=int(s.groups.UnitRoller.optDistAtt);
if(s.groups.UnitRoller.optJumpAtt!==undefined)(u as UnitRoller).optJumpAtt=Boolean(s.groups.UnitRoller.optJumpAtt);
}
if(u is UnitScythe && s.groups.UnitScythe!=null) {
if(s.groups.UnitScythe.napr!==undefined)(u as UnitScythe).napr=Number(s.groups.UnitScythe.napr);
if(s.groups.UnitScythe.dr!==undefined)(u as UnitScythe).dr=Number(s.groups.UnitScythe.dr);
if(s.groups.UnitScythe.t!==undefined)(u as UnitScythe).t=int(s.groups.UnitScythe.t);
if(s.groups.UnitScythe.por!==undefined)(u as UnitScythe).por=int(s.groups.UnitScythe.por);
if(s.groups.UnitScythe.bindRad!==undefined)(u as UnitScythe).bindRad=int(s.groups.UnitScythe.bindRad);
if(s.groups.UnitScythe.aiN!==undefined)(u as UnitScythe).aiN=int(s.groups.UnitScythe.aiN);
}
if(u is UnitSentinel && s.groups.UnitSentinel!=null) {
if(s.groups.UnitSentinel.jump_n!==undefined)(u as UnitSentinel).jump_n=int(s.groups.UnitSentinel.jump_n);
}
if(u is UnitSlime && s.groups.UnitSlime!=null) {
if(s.groups.UnitSlime.pluh!==undefined)(u as UnitSlime).pluh=int(s.groups.UnitSlime.pluh);
if(s.groups.UnitSlime.tr!==undefined)(u as UnitSlime).tr=int(s.groups.UnitSlime.tr);
if(s.groups.UnitSlime.isMine!==undefined)(u as UnitSlime).isMine=Boolean(s.groups.UnitSlime.isMine);
if(s.groups.UnitSlime.explDist!==undefined)(u as UnitSlime).explDist=Number(s.groups.UnitSlime.explDist);
if(s.groups.UnitSlime.isExpl!==undefined)(u as UnitSlime).isExpl=Boolean(s.groups.UnitSlime.isExpl);
if(s.groups.UnitSlime.aiN!==undefined)(u as UnitSlime).aiN=int(s.groups.UnitSlime.aiN);
}
if(u is UnitSpectre && s.groups.UnitSpectre!=null) {
if(s.groups.UnitSpectre.br!==undefined)(u as UnitSpectre).br=Number(s.groups.UnitSpectre.br);
}
if(u is UnitSpriteBot && s.groups.UnitSpriteBot!=null) {
if(s.groups.UnitSpriteBot.cDam!==undefined)(u as UnitSpriteBot).cDam=Number(s.groups.UnitSpriteBot.cDam);
if(s.groups.UnitSpriteBot.aiDx!==undefined)(u as UnitSpriteBot).aiDx=Number(s.groups.UnitSpriteBot.aiDx);
if(s.groups.UnitSpriteBot.aiDy!==undefined)(u as UnitSpriteBot).aiDy=Number(s.groups.UnitSpriteBot.aiDy);
if(s.groups.UnitSpriteBot.aiRasst!==undefined)(u as UnitSpriteBot).aiRasst=Number(s.groups.UnitSpriteBot.aiRasst);
}
if(u is UnitThunderHead && s.groups.UnitThunderHead!=null) {
if(s.groups.UnitThunderHead.shitMaxHp!==undefined)(u as UnitThunderHead).shitMaxHp=Number(s.groups.UnitThunderHead.shitMaxHp);
if(s.groups.UnitThunderHead.emit_t!==undefined)(u as UnitThunderHead).emit_t=int(s.groups.UnitThunderHead.emit_t);
if(s.groups.UnitThunderHead.moveX!==undefined)(u as UnitThunderHead).moveX=Number(s.groups.UnitThunderHead.moveX);
if(s.groups.UnitThunderHead.moveY!==undefined)(u as UnitThunderHead).moveY=Number(s.groups.UnitThunderHead.moveY);
if(s.groups.UnitThunderHead.t_atk!==undefined)(u as UnitThunderHead).t_atk=int(s.groups.UnitThunderHead.t_atk);
if(s.groups.UnitThunderHead.t_shit!==undefined)(u as UnitThunderHead).t_shit=int(s.groups.UnitThunderHead.t_shit);
if(s.groups.UnitThunderHead.kolth!==undefined)(u as UnitThunderHead).kolth=int(s.groups.UnitThunderHead.kolth);
if(s.groups.UnitThunderHead.speedBonus!==undefined)(u as UnitThunderHead).speedBonus=Number(s.groups.UnitThunderHead.speedBonus);
if(s.groups.UnitThunderHead.limX!==undefined)(u as UnitThunderHead).limX=int(s.groups.UnitThunderHead.limX);
if(s.groups.UnitThunderHead.limY!==undefined)(u as UnitThunderHead).limY=int(s.groups.UnitThunderHead.limY);
if(s.groups.UnitThunderHead.t_moln!==undefined)(u as UnitThunderHead).t_moln=int(s.groups.UnitThunderHead.t_moln);
if(s.groups.UnitThunderHead.isAtt!==undefined)(u as UnitThunderHead).isAtt=Boolean(s.groups.UnitThunderHead.isAtt);
if(s.groups.UnitThunderHead.kol_emit!==undefined)(u as UnitThunderHead).kol_emit=int(s.groups.UnitThunderHead.kol_emit);
if(s.groups.UnitThunderHead.max_emit!==undefined)(u as UnitThunderHead).max_emit=int(s.groups.UnitThunderHead.max_emit);
if(s.groups.UnitThunderHead.t_die!==undefined)(u as UnitThunderHead).t_die=int(s.groups.UnitThunderHead.t_die);
if(s.groups.UnitThunderHead.t_vsos!==undefined)(u as UnitThunderHead).t_vsos=int(s.groups.UnitThunderHead.t_vsos);
if(s.groups.UnitThunderHead.vsos_max!==undefined)(u as UnitThunderHead).vsos_max=int(s.groups.UnitThunderHead.vsos_max);
if(s.groups.UnitThunderHead.vsos_porog!==undefined)(u as UnitThunderHead).vsos_porog=int(s.groups.UnitThunderHead.vsos_porog);
if(s.groups.UnitThunderHead.vsos_force!==undefined)(u as UnitThunderHead).vsos_force=Number(s.groups.UnitThunderHead.vsos_force);
if(s.groups.UnitThunderHead.ugol!==undefined)(u as UnitThunderHead).ugol=Number(s.groups.UnitThunderHead.ugol);
if(s.groups.UnitThunderHead.distanc!==undefined)(u as UnitThunderHead).distanc=Number(s.groups.UnitThunderHead.distanc);
}
if(u is UnitThunderTurret && s.groups.UnitThunderTurret!=null) {
if(s.groups.UnitThunderTurret.bindX!==undefined)(u as UnitThunderTurret).bindX=Number(s.groups.UnitThunderTurret.bindX);
if(s.groups.UnitThunderTurret.bindY!==undefined)(u as UnitThunderTurret).bindY=Number(s.groups.UnitThunderTurret.bindY);
if(s.groups.UnitThunderTurret.attTurN!==undefined)(u as UnitThunderTurret).attTurN=int(s.groups.UnitThunderTurret.attTurN);
if(s.groups.UnitThunderTurret.t_wait!==undefined)(u as UnitThunderTurret).t_wait=int(s.groups.UnitThunderTurret.t_wait);
}
if(u is UnitTrain && s.groups.UnitTrain!=null) {
if(s.groups.UnitTrain.tr!==undefined)(u as UnitTrain).tr=int(s.groups.UnitTrain.tr);
}
if(u is UnitTransmitter && s.groups.UnitTransmitter!=null) {
if(s.groups.UnitTransmitter.cDam!==undefined)(u as UnitTransmitter).cDam=Number(s.groups.UnitTransmitter.cDam);
if(s.groups.UnitTransmitter.dist!==undefined)(u as UnitTransmitter).dist=Number(s.groups.UnitTransmitter.dist);
if(s.groups.UnitTransmitter.distdam!==undefined)(u as UnitTransmitter).distdam=Number(s.groups.UnitTransmitter.distdam);
if(s.groups.UnitTransmitter.upKoef!==undefined)(u as UnitTransmitter).upKoef=Number(s.groups.UnitTransmitter.upKoef);
if(s.groups.UnitTransmitter.prevKoef!==undefined)(u as UnitTransmitter).prevKoef=Number(s.groups.UnitTransmitter.prevKoef);
if(s.groups.UnitTransmitter.cep!==undefined)(u as UnitTransmitter).cep=int(s.groups.UnitTransmitter.cep);
}
if(u is UnitTrap && s.groups.UnitTrap!=null) {
if(s.groups.UnitTrap.rearm!==undefined)(u as UnitTrap).rearm=Boolean(s.groups.UnitTrap.rearm);
if(s.groups.UnitTrap.aiN!==undefined)(u as UnitTrap).aiN=int(s.groups.UnitTrap.aiN);
}
if(u is UnitTrigger && s.groups.UnitTrigger!=null) {
if(s.groups.UnitTrigger.status!==undefined)(u as UnitTrigger).status=int(s.groups.UnitTrigger.status);
if(s.groups.UnitTrigger.trapT!==undefined)(u as UnitTrigger).trapT=int(s.groups.UnitTrigger.trapT);
if(s.groups.UnitTrigger.ax1!==undefined)(u as UnitTrigger).ax1=Number(s.groups.UnitTrigger.ax1);
if(s.groups.UnitTrigger.ax2!==undefined)(u as UnitTrigger).ax2=Number(s.groups.UnitTrigger.ax2);
if(s.groups.UnitTrigger.ay1!==undefined)(u as UnitTrigger).ay1=Number(s.groups.UnitTrigger.ay1);
if(s.groups.UnitTrigger.ay2!==undefined)(u as UnitTrigger).ay2=Number(s.groups.UnitTrigger.ay2);
if(s.groups.UnitTrigger.trapL!==undefined)(u as UnitTrigger).trapL=int(s.groups.UnitTrigger.trapL);
if(s.groups.UnitTrigger.needSkill!==undefined)(u as UnitTrigger).needSkill=String(s.groups.UnitTrigger.needSkill);
if(s.groups.UnitTrigger.isAct!==undefined)(u as UnitTrigger).isAct=Boolean(s.groups.UnitTrigger.isAct);
if(s.groups.UnitTrigger.one!==undefined)(u as UnitTrigger).one=Boolean(s.groups.UnitTrigger.one);
if(s.groups.UnitTrigger.allid!==undefined)(u as UnitTrigger).allid=String(s.groups.UnitTrigger.allid);
if(s.groups.UnitTrigger.allact!==undefined)(u as UnitTrigger).allact=String(s.groups.UnitTrigger.allact);
if(s.groups.UnitTrigger.vNoise!==undefined)(u as UnitTrigger).vNoise=int(s.groups.UnitTrigger.vNoise);
if(s.groups.UnitTrigger.res!==undefined)(u as UnitTrigger).res=String(s.groups.UnitTrigger.res);
if(s.groups.UnitTrigger.aiN!==undefined)(u as UnitTrigger).aiN=int(s.groups.UnitTrigger.aiN);
}
if(u is UnitTurret && s.groups.UnitTurret!=null) {
if(s.groups.UnitTurret.turrettip!==undefined)(u as UnitTurret).turrettip=int(s.groups.UnitTurret.turrettip);
if(s.groups.UnitTurret.hidden!==undefined)(u as UnitTurret).hidden=int(s.groups.UnitTurret.hidden);
if(s.groups.UnitTurret.sleep!==undefined)(u as UnitTurret).sleep=Boolean(s.groups.UnitTurret.sleep);
if(s.groups.UnitTurret.reprog!==undefined)(u as UnitTurret).reprog=Boolean(s.groups.UnitTurret.reprog);
if(s.groups.UnitTurret.actDrot!==undefined)(u as UnitTurret).actDrot=Number(s.groups.UnitTurret.actDrot);
if(s.groups.UnitTurret.noTurn!==undefined)(u as UnitTurret).noTurn=Boolean(s.groups.UnitTurret.noTurn);
if(s.groups.UnitTurret.absVis!==undefined)(u as UnitTurret).absVis=Boolean(s.groups.UnitTurret.absVis);
if(s.groups.UnitTurret.watchDrot!==undefined)(u as UnitTurret).watchDrot=Number(s.groups.UnitTurret.watchDrot);
if(s.groups.UnitTurret.period!==undefined)(u as UnitTurret).period=int(s.groups.UnitTurret.period);
if(s.groups.UnitTurret.nRot!==undefined)(u as UnitTurret).nRot=int(s.groups.UnitTurret.nRot);
if(s.groups.UnitTurret.angle!==undefined)(u as UnitTurret).angle=String(s.groups.UnitTurret.angle);
}
if(u is UnitVortex && s.groups.UnitVortex!=null) {
if(s.groups.UnitVortex.br!==undefined)(u as UnitVortex).br=Number(s.groups.UnitVortex.br);
}
if(u is UnitZebra && s.groups.UnitZebra!=null) {
if(s.groups.UnitZebra.shine!==undefined)(u as UnitZebra).shine=int(s.groups.UnitZebra.shine);
if(s.groups.UnitZebra.shine2!==undefined)(u as UnitZebra).shine2=int(s.groups.UnitZebra.shine2);
if(s.groups.UnitZebra.red!==undefined)(u as UnitZebra).red=Boolean(s.groups.UnitZebra.red);
}
if(u is UnitZombie && s.groups.UnitZombie!=null) {
if(s.groups.UnitZombie.superX!==undefined)(u as UnitZombie).superX=Number(s.groups.UnitZombie.superX);
if(s.groups.UnitZombie.superY!==undefined)(u as UnitZombie).superY=Number(s.groups.UnitZombie.superY);
if(s.groups.UnitZombie.glowTip!==undefined)(u as UnitZombie).glowTip=int(s.groups.UnitZombie.glowTip);
if(s.groups.UnitZombie.knocked2!==undefined)(u as UnitZombie).knocked2=Number(s.groups.UnitZombie.knocked2);
if(s.groups.UnitZombie.superSilaTip!==undefined)(u as UnitZombie).superSilaTip=int(s.groups.UnitZombie.superSilaTip);
if(s.groups.UnitZombie.tZlo!==undefined)(u as UnitZombie).tZlo=int(s.groups.UnitZombie.tZlo);
if(s.groups.UnitZombie.tPrepSuper!==undefined)(u as UnitZombie).tPrepSuper=int(s.groups.UnitZombie.tPrepSuper);
if(s.groups.UnitZombie.tSuper!==undefined)(u as UnitZombie).tSuper=int(s.groups.UnitZombie.tSuper);
if(s.groups.UnitZombie.vJump!==undefined)(u as UnitZombie).vJump=int(s.groups.UnitZombie.vJump);
if(s.groups.UnitZombie.teleAccel!==undefined)(u as UnitZombie).teleAccel=Number(s.groups.UnitZombie.teleAccel);
if(s.groups.UnitZombie.teleSpeed!==undefined)(u as UnitZombie).teleSpeed=Number(s.groups.UnitZombie.teleSpeed);
if(s.groups.UnitZombie.vDestroy!==undefined)(u as UnitZombie).vDestroy=Number(s.groups.UnitZombie.vDestroy);
if(s.groups.UnitZombie.radMin!==undefined)(u as UnitZombie).radMin=int(s.groups.UnitZombie.radMin);
if(s.groups.UnitZombie.radMax!==undefined)(u as UnitZombie).radMax=int(s.groups.UnitZombie.radMax);
if(s.groups.UnitZombie.radradMin!==undefined)(u as UnitZombie).radradMin=int(s.groups.UnitZombie.radradMin);
if(s.groups.UnitZombie.radradMax!==undefined)(u as UnitZombie).radradMax=int(s.groups.UnitZombie.radradMax);
if(s.groups.UnitZombie.radHeal!==undefined)(u as UnitZombie).radHeal=Number(s.groups.UnitZombie.radHeal);
if(s.groups.UnitZombie.superQuake!==undefined)(u as UnitZombie).superQuake=Number(s.groups.UnitZombie.superQuake);
if(s.groups.UnitZombie.super_on!==undefined)(u as UnitZombie).super_on=Boolean(s.groups.UnitZombie.super_on);
if(s.groups.UnitZombie.tIsRes!==undefined)(u as UnitZombie).tIsRes=int(s.groups.UnitZombie.tIsRes);
if(s.groups.UnitZombie.t_res!==undefined)(u as UnitZombie).t_res=int(s.groups.UnitZombie.t_res);
if(s.groups.UnitZombie.t_ca!==undefined)(u as UnitZombie).t_ca=int(s.groups.UnitZombie.t_ca);
if(s.groups.UnitZombie.aiJump!==undefined)(u as UnitZombie).aiJump=int(s.groups.UnitZombie.aiJump);
if(s.groups.UnitZombie.aiZlo!==undefined)(u as UnitZombie).aiZlo=int(s.groups.UnitZombie.aiZlo);
if(s.groups.UnitZombie.optDistAtt!==undefined)(u as UnitZombie).optDistAtt=int(s.groups.UnitZombie.optDistAtt);
}
}
}
}
