"""Generate compile-only declarations and typed package access from the 1.02 reference.
No reference or game files are modified. Run only when reviewing the native fields.
"""
from pathlib import Path
import re

root = Path(__file__).resolve().parents[1]
reference = root.parents[1] / 'game-reference/decompiled/1.02/src102/scripts/fe/unit'
classes = {}
for path in sorted(list(reference.glob('Unit*.as'))+[reference/'Mine.as']):
    source = path.read_text(encoding='utf-8-sig')
    name = path.stem
    if name in ('UnitPlayer', 'UnitPet', 'UnitPlayerOrig'):
        continue
    match = re.search(r'public class \w+(?: extends (\w+))?', source)
    if not match:
        continue
    fields = re.findall(r'internal var (\w+):(int|uint|Number|Boolean|String)\b', source)
    # Rendering caches and audio do not describe simulation; copying them breaks visuals.
    fields = [(n,t) for n,t in fields if not n.startswith(('blit', 'snd', 'ctrans', 'visDam'))]
    classes[name] = (match.group(1), fields)

capture = ['package fe.unit {', 'public class RConnectUnitAccess {',
           'public static function capture(u:Unit):Object {',
           'var s:Object={xml:u.mapxml==null?null:u.mapxml.toXMLString(),ai:u.aiState,groups:{}};']
restore = ['public static function restore(u:Unit,s:Object):void {', 'if(s==null || s.groups==null)return;']
for name, (parent, fields) in classes.items():
    if name != 'Unit':
        parent = parent if parent in classes else 'Unit'
        declarations = '\n'.join(f'internal var {n}:{t};' for n,t in fields)
        (root / f'tools/stubs/fe/unit/{name}.as').write_text(
            f'package fe.unit {{ public class {name} extends {parent} {{\n{declarations}\n}} }}\n', encoding='utf-8')
    else:
        declarations = '\n'.join(f'internal var {n}:{t};' for n,t in fields)
        (root / 'tools/stubs/fe/unit/Unit.as').write_text('''package fe.unit {
import fe.weapon.Bullet;
// Compile-only external declarations. Never embedded in the production SWF.
public class Unit {
internal var mapxml:XML;
''' + declarations + '''
public function Unit(id:String=null,difficulty:Number=100,map:XML=null,data:Object=null) {}
public function damage(amount:Number,type:int,bullet:Bullet=null,periodic:Boolean=false):Number {return 0;}
public function die(type:int=0):* {}
} }
''', encoding='utf-8')
    if not fields:
        continue
    capture += [f'if(u is {name}) s.groups.{name}={{' + ','.join(f'{n}:(u as {name}).{n}' for n,t in fields) + '};']
    restore += [f'if(u is {name} && s.groups.{name}!=null) {{']
    restore += [f'if(s.groups.{name}.{n}!==undefined)(u as {name}).{n}={t}(s.groups.{name}.{n});' for n,t in fields]
    restore += ['}']
capture += ['return s;', '}']
restore += ['}', '}', '}']
(root / 'src/fe/unit/RConnectUnitAccess.as').write_text(
    '// Generated by tools/generate_room_access.py; native simulation scalars only.\n' + '\n'.join(capture+restore)+'\n', encoding='utf-8')
print(f'{len(classes)} external classes; package accessor generated')
